{% set name = "ansys-pythonnet" %}
{% set version = "3.1.0rc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansys-pythonnet-{{ version }}.tar.gz
  sha256: 6b696529197aaaf0a0f0e31e0fea2a9c0fe53e33e6f73dfdedb940196f03abf5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - dotnet ~=7.0
    - mono  # [not win]
    - python
    - setuptools >=61
    - wheel
    - pip
  run:
    - python
    - clr_loader >=0.2.6,<0.3.0
    - mono  # [not win]
    - dotnet ~=7.0

test:
  imports:
    - pythonnet
  commands:
    - pip check
  requires:
    - pip

about:
  summary: .NET and Mono integration for Python (Ansys, Inc. fork)
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/ansys-pythonnet/
  summary: Ansys fork of pythonnet
  dev_url: https://github.com/ansys/ansys-pythonnet

extra:
  recipe-maintainers:
    - koubaa
    - SMoraisAnsys
