{% set name = "ansys-pythonnet" %}
{% set version = "3.1.0rc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_pythonnet-{{ version }}.tar.gz
  sha256: 8ae09cf7687a7b431f41f570d12bd7547e393618231d0ef877fe021d491fc945

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py>=314]

requirements:
  build:
    - dotnet-sdk ~=7.0
  host:
    - python
    - setuptools >=61
    - wheel
    - pip
  run:
    - clr_loader >=0.2.6,<0.3.0
    - mono  # [not win]
    - dotnet-runtime ~=7.0
    - python

test:
  imports:
    - pythonnet
  commands:
    - pip check
  requires:
    - pip

about:
  summary: .NET and Mono integration for Python (Ansys, Inc. fork)
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/ansys-pythonnet/
  dev_url: https://github.com/ansys/ansys-pythonnet

extra:
  recipe-maintainers:
    - koubaa
    - SMoraisAnsys
