context:
  name: "ansys-pythonnet"
  version: "3.1.0rc3"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ansys-pythonnet-${{ version }}.tar.gz
  sha256: 369a0a5a838a0991f755b6d63c319ab6997f9dc464d016187227be5cd860a9cb

build:
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - dotnet-sdk >=6
  host:
    - if: not win
      then: mono
    - python
    - setuptools >=61
    - wheel
    - pip
  run:
    - python
    - clr_loader >=0.2.6,<0.3.0
    - if: not win
      then: mono
    - dotnet-runtime

tests:
  - python:
      imports:
      - pythonnet
      pip_check: true

about:
  summary: '.NET and Mono integration for Python (Ansys, Inc. fork)'
  homepage: https://pypi.org/project/ansys-pythonnet/
  repository: https://github.com/ansys/ansys-pythonnet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - koubaa
    - SMoraisAnsys
